language: node_js

node_js: stable

cache:
  directories:
     - node_modules

branches:
    only:
       - master

before_install:
   - git checkout none

install:
   - npm install hexo-cli -g

script:
   - mkdir dir;cd dir;hexo init;cd ..

after_success:
   - git config --global user.name "${username}"
   - git config --global user.email "${useremail}"
   - git add .
   - git commit -m "Travis CI Auto Builder `date`"
   - git push --quiet origin master